In [23]:
#Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

In [77]:
#Import 'Songs_Radio_FINAL.csv' file in the Datasets folder on the local machine

SongsRadioTest = pd.read_csv('Songs_Radio_FINAL.csv')
SongsRadioTest.head()

                       ARTIST              SONG  ... NEWS SERVICE    STATION
0                Foo Fighters  Waiting on a War  ...            0  Comercial
1  DJ Snake ft. Justin Bieber   Let Me Love You  ...            0  Comercial
2                        Syro           Acordar  ...            0  Comercial
3               Amy Winehouse             Rehab  ...            0  Comercial
4                    Maroon 5          Memories  ...            0  Comercial

[5 rows x 13 columns]

In [78]:
#shape of the dataframe
SongsRadioTest.shape

(1113, 13)

In [79]:
#data types
SongsRadioTest.dtypes

ARTIST            object
SONG              object
FORM              object
LANGUAGE          object
YEAR               int64
DECADE             int64
VIEWS YOUTUBE    float64
DATE              object
HOUR              object
GROUP HOUR         int64
SHOW              object
NEWS SERVICE       int64
STATION           object
dtype: object

In [80]:
#For better manipulation, let's change also the date and time variables to datetime variables
#let's change the object variables into string variables (?)


# convert date and Hour columns to datetime format
#SongsRadioTest['DATE'] = pd.to_datetime(SongsRadioTest['DATE'])
#SongsRadioTest['HOUR'] = SongsRadioTest['HOUR'].map(lambda x: pd.to_datetime(x, errors='coerce'))


# convert object variables into string variables



#Help Links: 
#To Convert Hour into datetime: https://stackoverflow.com/questions/39584118/dask-dataframe-how-to-convert-column-to-to-datetime
#To Convert Date into datetime: https://stackoverflow.com/questions/39584118/dask-dataframe-how-to-convert-column-to-to-datetime

In [81]:
#Change the name of the HOUR column to DATE & HOUR
#Delete DATE column

SongsRadioTest = SongsRadioTest.rename(columns={'HOUR':'DATE & HOUR'})
#del SongsRadioTest['DATE']


#Final Result dtype
SongsRadioTest.dtypes

ARTIST                   object
SONG                     object
FORM                     object
LANGUAGE                 object
YEAR                      int64
DECADE                    int64
VIEWS YOUTUBE           float64
DATE & HOUR      datetime64[ns]
GROUP HOUR                int64
SHOW                     object
NEWS SERVICE              int64
STATION                  object
dtype: object

In [82]:
#Final Result Dataframe
SongsRadioTest

                          ARTIST  ...     STATION
0                   Foo Fighters  ...   Comercial
1     DJ Snake ft. Justin Bieber  ...   Comercial
2                           Syro  ...   Comercial
3                  Amy Winehouse  ...   Comercial
4                       Maroon 5  ...   Comercial
...                          ...  ...         ...
1108                Phil Collins  ...  Renascença
1109                      Police  ...  Renascença
1110                    Bon Jovi  ...  Renascença
1111                          U2  ...  Renascença
1112                      Limahl  ...  Renascença

[1113 rows x 12 columns]

In [83]:
#General Overview
SongsRadioTest.describe()

              YEAR       DECADE  VIEWS YOUTUBE   GROUP HOUR  NEWS SERVICE
count  1113.000000  1113.000000   2.130000e+02  1113.000000   1113.000000
mean   2005.501348  2001.983827   1.945815e+08    10.567835      0.639712
std      14.813233    15.918342   3.872264e+08     6.890141      0.480300
min    1965.000000  1960.000000   2.169300e+04     0.000000      0.000000
25%    1992.000000  1990.000000   3.857888e+06     4.000000      0.000000
50%    2009.000000  2000.000000   4.143842e+07    11.000000      1.000000
75%    2020.000000  2020.000000   1.809699e+08    16.000000      1.000000
max    2021.000000  2020.000000   2.855508e+09    23.000000      1.000000

In [84]:
# checking for missing values
SongsRadioTest.isnull().sum()

ARTIST             0
SONG               0
FORM               0
LANGUAGE           0
YEAR               0
DECADE             0
VIEWS YOUTUBE    900
DATE & HOUR        0
GROUP HOUR         0
SHOW               0
NEWS SERVICE       0
STATION            0
dtype: int64

In the VIEWS YOUTUBE column, there are 900 missing values. That's because in this column, we only picked a sample of 30 songs from every radio station. The sample did have repetitions and some songs played several times during the day.

In [85]:
SongsRadioTest

                          ARTIST  ...     STATION
0                   Foo Fighters  ...   Comercial
1     DJ Snake ft. Justin Bieber  ...   Comercial
2                           Syro  ...   Comercial
3                  Amy Winehouse  ...   Comercial
4                       Maroon 5  ...   Comercial
...                          ...  ...         ...
1108                Phil Collins  ...  Renascença
1109                      Police  ...  Renascença
1110                    Bon Jovi  ...  Renascença
1111                          U2  ...  Renascença
1112                      Limahl  ...  Renascença

[1113 rows x 12 columns]

In [87]:
#The Date accidentaly changed to current (2021-07-19). I need to correct this.

SongsRadioTest1 = SongsRadioTest

SongsRadioTest1['DATE & HOUR'] = pd.to_datetime(SongsRadioTest1['DATE & HOUR'])
SongsRadioTest1['DATE & HOUR'] = SongsRadioTest1['DATE & HOUR'].apply(lambda x: x.replace(day = x.day - 7))


#Help Link
#https://stackoverflow.com/questions/53137642/changing-years-in-a-date-column

In [88]:
SongsRadioTest1

                          ARTIST  ...     STATION
0                   Foo Fighters  ...   Comercial
1     DJ Snake ft. Justin Bieber  ...   Comercial
2                           Syro  ...   Comercial
3                  Amy Winehouse  ...   Comercial
4                       Maroon 5  ...   Comercial
...                          ...  ...         ...
1108                Phil Collins  ...  Renascença
1109                      Police  ...  Renascença
1110                    Bon Jovi  ...  Renascença
1111                          U2  ...  Renascença
1112                      Limahl  ...  Renascença

[1113 rows x 12 columns]

In [89]:
# general overview again

SongsRadioTest1.describe()

              YEAR       DECADE  VIEWS YOUTUBE   GROUP HOUR  NEWS SERVICE
count  1113.000000  1113.000000   2.130000e+02  1113.000000   1113.000000
mean   2005.501348  2001.983827   1.945815e+08    10.567835      0.639712
std      14.813233    15.918342   3.872264e+08     6.890141      0.480300
min    1965.000000  1960.000000   2.169300e+04     0.000000      0.000000
25%    1992.000000  1990.000000   3.857888e+06     4.000000      0.000000
50%    2009.000000  2000.000000   4.143842e+07    11.000000      1.000000
75%    2020.000000  2020.000000   1.809699e+08    16.000000      1.000000
max    2021.000000  2020.000000   2.855508e+09    23.000000      1.000000

In [90]:
#Save cleaned dataset to csv
SongsRadioTest1.to_csv('Songs_Radio_FINAL_CLEANED.csv')

In [92]:
#Download cleaned dataset to local machine
from google.colab import files
files.download("Songs_Radio_FINAL_CLEANED.csv")